### ISSUE TITLE
project references

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#1]
Standardize the method on how the SE assemblies are referenced in the project/s, so we don't have to keep rewriting the project on one another.

suggestions:
Create a symbolic link to where ever your Steam SE bin64 path is, back to c:\program files...

**Comment by Spcemarine** [comment]
Done as you suggested. Assemblies will refer to "C:\Program Files\Reference
Assemblies\SpaceEngineers". See 46eec10ad184b21ddefc45e52baba573e0189c08 for additional information.
