### ISSUE TITLE
Mod won't work

### ISSUE THREAD

**Issue by aschmois** [midspace/Space-Engineers-Admin-script-mod#103]
Tried in dedicated server, and creating a new local (multiplayer) game. Mod says added (mod list shows as 1) and no errors are thrown. But when I go into the console, any commands I type (including non-admin commands) I get a syntax error.

**Comment by aschmois** [comment]
Idiot me... I kept thinking I needed the console instead of regular chat...

**Comment by midspace** [comment]
For my interest, what console were you trying to use?

**Comment by aschmois** [comment]
Alt + ~, available only in multiplayer
