### ISSUE TITLE
BUG: /motd seems to only display the end of the motd message and misses the start

### ISSUE THREAD

**Issue by jpcsupplies** [midspace/Space-Engineers-Admin-script-mod#127]
Since the update our admin mod MOTD message has cut off the first pages, all i get is the last page

**Comment by jpcsupplies** [comment]
Appears the issue is common to all invokes of MyAPIGateway.Utilities.ShowMissionScreen("Economy Help", "", "sell command", helpreply, null, "Close");

appears to be a keen issue..  have reported as bug..  suggest flag this wontfix and close if keen fixes it

**Comment by midspace** [comment]
Cannot fix.
