### ISSUE TITLE
/stopall command throws an error window

### ISSUE THREAD

**Issue by jpcsupplies** [midspace/Space-Engineers-Admin-script-mod#128]
appears to be related to using space manager, although I am back in my body when it occurs..

basically scanning fast moving distant objects find a drifting ship, exit space most ctrl-space my body there F6 back to my body and /stopall 1000 and it throws error, not sure exact error couldnt cut paste it

**Comment by midspace** [comment]
I haven't been able to reproduce this as yet.

**Comment by DigTron** [comment]
```
Sandbox.Game.Entities.MyTrashRemoval.ApplyOperation(Sandbox.Game.Entities.MyEntity entity, Sandbox.Game.Entities.MyTrashRemovalOperation operation)
```

```
public enum MyTrashRemovalOperation
  {
    None = 0,
    Remove = 1,
    Stop = 2,
    Depower = 4,
  }
```

May prove to be quite useful.... remove seems to do the usual .close() on the entity, nothing new there. But stop and depower may help if your implementations of those methods run into trouble.

I have seen no issues with those commands, but also haven't been testing them.

....I also havent even confirmed if you can even use that class or enum in mods.... just came to mind when I saw this so felt it was worth mentioning.

**Comment by midspace** [comment]
Thanks, I'll look into it.

There are quite a few Space Engineers classes that are in the whitelist but don't have an Interface exposing them directly.

**Comment by midspace** [comment]
I haven't been able to reproduce this error.
I'm closing the issue.
