### ISSUE TITLE
Conflict with SEServer Extender Essentials Plugin

### ISSUE THREAD

**Issue by stephen-cernota** [midspace/Space-Engineers-Admin-script-mod#139]
As a server admin, I love the functionality of [SEServerExtender](https://github.com/rexxar-tc/SEServerExtender) with the [Essentials Plugin](https://github.com/rexxar-tc/EssentialsPlugin) and the [Midspace Admin Script Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=316190120), unfortunately it looks like Essentials and Midspace Admin do not play well together, how could we move forward?

References:
- https://github.com/rexxar-tc/EssentialsPlugin/issues/29#issuecomment-166475392
- http://forum.keenswh.com/threads/se-server-extender-and-essentials-help-thread.7374427/page-2#post-1286901340

**Comment by midspace** [comment]
We have a permissions system, so it is possible to turn off a command.
https://github.com/midspace/Space-Engineers-Admin-script-mod/wiki/Permissions
`/perm command setlevel motd 999`

However, I think it still responds to messages with a security warning.
Is it possible for you to check this?

What we could do, it set it so it no longer blocks a message when no one has access.

**Comment by Spcemarine** [comment]
We could allow custom command names that override the old names. That way admins could give certain commands other names and thus the commands of other tools could be used.

**Comment by midspace** [comment]
Weird, I'm sure I posted a comment earlier.

Keen have already released this week's update.
I'll post an update when I get home.

**Comment by midspace** [comment]
I have published an update of the Admin mod with the enhancement.

Please test with SE Server Extender before I close this issue.
I have described in the change comments, use the following to disable the /motd in the Admin helper mod:
`/perm command setlevel motd none`

If you wish to re-enable it, use:
`/perm command setlevel motd 100`

**Comment by rexxar-tc** [comment]
You'll want to go grab the latest Essentials update if you want to test this mod. Old versions looked for it and disabled some commands.

Thanks, Midspace :)

**Comment by midspace** [comment]
What other commands does Server Extender and Essentials use that Admin helper mod conflict over?

**Comment by rexxar-tc** [comment]
/settings and /help. I had to disable them because of an issue I was having with the communication relays those commands can create. I fixed it some time ago, so it should be safe either way. (besides, I need to remove the relays, it's an outdated method)

**Comment by midspace** [comment]
Has this bug been fixed?
Is there any further issues with conflicts with SEServer Extender?
Can I close this issue? :smile:

**Comment by rexxar-tc** [comment]
As far as I know there aren't any issues. I haven't received any reports, at least.

Actually, now I think about it, the new chat command system in SESE takes care of conflicts. I'll let you know if any do pop up ;)

**Comment by midspace** [comment]
Okay, I'll close this. It can always be reopened or a new bug logged.
