### ISSUE TITLE
MOTD works incorrectly with cyrillic symbols

### ISSUE THREAD

**Issue by GornyakManiac** [midspace/Space-Engineers-Admin-script-mod#148]
Does MOTD support cyrillic messages? I tried to set motd on russian and there is what i've got:

http://images.akamai.steamusercontent.com/ugc/352773107413152670/7D47D22F0B02C9B3D3944FFE09F597F0990D6E77/

**Comment by GornyakManiac** [comment]
I don't now why, but encoding by UTF-16 sets by default in mod config files. I changed it to UTF-8 and text showed up correctly, but mod changes it back automatically after some time :((((

**Comment by Spcemarine** [comment]
This definitely looks like some issue with the encoding. So you say that you set the UTF-16 manually and it works but when the mod overwrites the file it will be set back to UTF-8?

**Comment by GornyakManiac** [comment]
In reverse :) I set it manually to UTF-8, by default there was UTF-16

**Comment by Spcemarine** [comment]
Ok, that makes more sense and I think I just misread it. ;)

@midspace any ideas? I mean we're using the UTF-16 encoding to send messages, there shouldn't be any loss if we have a UTF-8 source...

**Comment by midspace** [comment]
I am confused.
Are we talking about the MOTD file?
Or are we talking about the config files?

The MOTD file is in plain text. Not xml.
For support of cyrillic, make sure to use an application that supports Unicode.
Windows notepad.exe supports these. Many other applications do not.
Either save with Unicode or UTF-8 encoding.
"File", "Save As", Choose the Encoding as "Unicode", and "Save".


The Mod will automatically save the motd file back to the most compatible encoding.
If there are only ansi characters, then it will save the file to Ansi Encoding.
If there are minimal extended characters (like cyrillic), then it will save to UTF-8.
If there are long extended characters (like chinese), then it will save to Unicode.

Config files should be modified by in game commands wherever possible.

Now, if this is set up on a Hosted multiplayer (not dedicated server), and the host sees the correct cyrillic message, but other players see ????????, then it's a problem with the serializing/deserializing and messaging system.
Which is a problem as we have very limited control over this.

We specifically use Encoding.Unicode.GetString and Encoding.Unicode.GetBytes to preserve extended characters, so I don't expect to see an issue there.

I might look at prompting Keen for that API.

**Comment by GornyakManiac** [comment]
For now I can't reproduce that issue, MOTD works fine, but I've done nothing except changing UTF-16 to UTF-8 in mod config file and editing MOTD file on my own PC in UTF-8. I think ANSI encoding is set in my DS' windows notepad by default but I'm not sure that this is so. I'll write if I find out that this is issue of mod.

**Comment by serjkrog** [comment]
Hi!
I'm also had this issue and resolved it.

1) Completely stop the server with mod activated.
2) Open motd message file in editor like Notepad++ and convert all text to UTF-8 w/o BOM 
3) Save the moth file and run SE
4) Enjoy.

**Comment by midspace** [comment]
There has been no further updates of this issue, so I'm closing it as resolved.
