### ISSUE TITLE
[Feature request] Command for trash removal

### ISSUE THREAD

**Issue by ChrisM-Rogers** [midspace/Space-Engineers-Admin-script-mod#149]
I would fork the code and try to add it my self and then send it in to you guys, but I'm a bit busy with my own projects at the moment. But if I have time I'll give it a go. 

I find that the auto trash removal option doesn't really work as good as it could, therefore I'd like a command to manually remove uneeded trash. I know theres already `/countobjects`, `/pullobjects` and `/collectobjects`, but when there's 100+ objects sitting infront of you, its a bit boring and time consuming picking them all up, espcially if it's large chunks of ore the fill your inventory rather quickly. 

Therefore I feel something like `/removetrash` would be a great addition to the already great list of commands.

**Comment by midspace** [comment]
Low floating objects limits should be applied to prevent this.

We can implement a /deleteobjects command to simply delete the floating objects if that is exactly what you need.

Unless you are looking for a more global trash cleanup?
There was something mention by DigTron here, which potentially allows use to implement Trash cleanup routines for ships also.
https://github.com/midspace/Space-Engineers-Admin-script-mod/issues/128

**Comment by ChrisM-Rogers** [comment]
Yeah I was aiming more at a global one, sorry I should have specified. I guess this request can be deleted since there's already one here for it, I just didn't see it when I did a search.

**Comment by midspace** [comment]
The `/delobjects` command has been added.
