### ISSUE TITLE
Teleport player to player

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#15]
Command to teleport one specified player to another specified player.

Need to check Player/Character position if player is controlling Remote, and teleport appropriately.

**Comment by Spcemarine** [comment]
With the current logic it would be named 'tppp'... And it will be followed by 'tpps', 'tpsp' and 'tpss'... and don't forget 'tppc' (teleport player to coordinates)... Well, I must say, as a normal user it'd kind of deter me. It's quite confusing. I wonder if we should write an algorithm that can detect which case it must handle. If we assumed that we have only 'tp' left with all it's possibilities, like an *all in one* teleport command, it'd require that we change the hotlists a bit. I like the was the bot hotlist works. If we use S for ship and P for player, it could work with only one command. E.g. '/tp P1', '/tp S2' '/tp P1 P2', /tp P4 S4', 'tp x y z'. Also it implies the logic that if I have the minimum arguments, I am the one to be teleported/stopped/killed/whatever, what keeps it quite simple. We could export this logic to all commands in the mod, e.g. '/stop' doesn't use it. Instead it'll refer to the object I'm looking at. Well, aiming while typing '/stop' seems pretty difficult for me. ;-)

These are just some thoughts around midnight, at the moment I think it's quite reasonable but that can change tomorrow. I just want to let it here. Maybe you like the ideas.

**Comment by midspace** [comment]
All teleport dommands so far have been to teleport the current player to another location.

I was thinking just now, just extend the current commands, adding an optional hotlist.
So, /tp is coordinates. Adding P123 or S123 to teleport a player or ship to coordinates.
/tps teleports to a ship, so again teleporting a player or ship to another ship.

The concern is name complexity. The tps for instance allows specifying the ship name.
If you can't get both ships on your filter for a ship hot list, then you have to use names.
But I haven't done any "Quote" seperation, to simplify the process.

Perhaps making a single teleport command does remove a lots of the confusion.
Simply specify source and target. If there is only one entity specified, then we're going to assume the player is the source.

It does raise my concern about conflicting names. Ie, a player or ship has a name of "S123", or a ship has the same name as a player.
We cannot risk a teleport if we cannot be assured there is only one entity of the specified name.

/stop does allows for the specifying of the ship name also.

But, yes I think we can try for a global /tp command.
It might make sense to leave the existing commands for clarity, especially offset.
Offset is very player deterministic, as it relies upon the player direction or occupied cockpit direction.

Okay, here are the required parameters as I see it for the revamped command.
Sources:
None.
Quoted string. (Full or partial unique match)
Single unquoted string. (Full or partial unique match)
S# hotlist code.
P# hotlist code.

Destinations:
X,Y,Z coordinate.
Quoted string. (Full or partial unique match)
Single unquoted string. (Full or partial unique match)
S# hotlist code.
P# hotlist code.

**Comment by Spcemarine** [comment]
When we have conflicting names, we could create a hotlist containing the concerned entities, so the player'd just have to choose which one he needs and, of course, typing in the command again. That'd also help with the problem of the name complexity. But in the end, I think, 'escape sequences'/quotes will be necessary.

**Comment by midspace** [comment]
Closing this, as it is functionally complete.
