### ISSUE TITLE
Feature Request, shutdown/restart function

### ISSUE THREAD

**Issue by EngineerBean** [midspace/Space-Engineers-Admin-script-mod#154]
Just a small request of a shutdown/restart command that would save game and force a close. Which in my case I have a batch file that would start server again.

**Comment by midspace** [comment]
There isn't any internal command to shutdown or restart a server via the API.
We could intentionally crash the server, but I would not recommend that at all, as you risk corrupting the save file if it happened during the save.

**Comment by EngineerBean** [comment]
ok, no worries. Thanks for the quick response.

**Comment by FabioZumbi12** [comment]
Hi midspace,
Just to know, still the API dont allowing to restart the game?

**Comment by midspace** [comment]
The server does not have any functionality to restart. KeenSWH need to add this first before they can add the API.
