### ISSUE TITLE
Feature Request | Spawn blueprints?

### ISSUE THREAD

**Issue by Raided** [midspace/Space-Engineers-Admin-script-mod#155]
Is it possible to implement the spawning of blueprints, the same way as you spawn prefabs?

**Comment by Spcemarine** [comment]
Why is pasting the BP in the normal way insufficient?

**Comment by midspace** [comment]
If you have Admin access in game, you can use the game's Space Master feature both in single and multi player.
Press ALT F10, check the box up the top right of the screen.
Press ALT F10 to close.
Press SHIFT F10 to open the blueprints screen.
Select your blueprint.
Paste your blueprint.
Enter Space Master again with ALT F10, and turn it off again.


A mod cannot implement it any better than this.
We will continue to provide commands for creating a ship from prefabs, as the game itself doesn't allow a method for spawning ships from prefabs.

**Comment by Raided** [comment]
Sorry, I was unaware of this. Thank you for replying so quick.
