### ISSUE TITLE
Admin issue

### ISSUE THREAD

**Issue by eyeballs66** [midspace/Space-Engineers-Admin-script-mod#158]
before I installed this admin mod on my server I was full admin. Now that this mod was installed, I am not an admin and I cannot add or change anything because it says I do not have permission to change anything. If you can help it would be appreciated. Thanks

**Comment by Spcemarine** [comment]
First of all, our mod does not apply any changes to your status as an admin. Either you weren't admin before or the permissions of the mod are misconfigured. Did you verify your status with the F3 screen? If you press F3 a screen will open, with a list of all players on the server. In that list one column indicates who is server admin and who is not. If you are an admin, there will be five stars in that field.
If you are not an admin, check the list of admins in your server configuration and make sure you add yourself as a server admin.

**Comment by eyeballs66** [comment]
Yea i verified my status. Now i went and manually deleted the folder it created in my server storage folder and tried re loading it back in and it doesn't work at all now lol.. Don't know what what happened.

**Comment by eyeballs66** [comment]
I pressed F3 and i was not admin anymore after i loaded the mod in.

**Comment by Spcemarine** [comment]
Hmm... As we do not edit the config I don't really understand why the mod would be responsible. By the way, how did you notice that you weren't admin anymore?

**Comment by midspace** [comment]
To help us investigate this issue, could you plase attach:
1. A copy of the world.
2. A copy of the server log file after you have connected to the world (with the admin mod installed).
3. A copy of the server log file after you have connected to the world (with the admin mod NOT installed).

**Comment by eyeballs66** [comment]
Okay I got it to work now. I am trying to add someone as admin but now full admin rights is there a way I can do this through a command or do I have to add them through the server cfg file?

**Comment by Spcemarine** [comment]
Then you might wan to take a look at our [permissions](https://github.com/midspace/Space-Engineers-Admin-script-mod/wiki/Permissions). Can this issue be closed then? :)

**Comment by midspace** [comment]
Closing this issue, as the issue listed in the opening post has been resolved.
