### ISSUE TITLE
Admin Issue

### ISSUE THREAD

**Issue by Ardyfact** [midspace/Space-Engineers-Admin-script-mod#173]
I did seen an old Admin Issue but i did not see a fix for my problem.

In shared world admin commands work just fine.
In dedicated server admin commands do not work.
This world was copied and pasted from SE to SE,DS in appdata.

Things i checked.

My name in the admin tab of the DS start up.
F3 does not show me as an admin on DS, put does in shared world.
I deleted the server file then restarted new world. nothing.

any ideas on why this is not working. i feel like i am missing a simple install thing that i need to do.

**Comment by midspace** [comment]
You need to add the unique SteamID of any players you want to be Admin into the Dedicated Server configuration.
If you are using the `SpaceEngineersDedicated.exe` application supplied by Keen ( and not a Hosting service), then you should add it here:
![sedsadmin](https://cloud.githubusercontent.com/assets/6026063/20419627/fed92cd2-adab-11e6-8809-017acf20f06d.jpg)

To find your SteamID :
https://www.google.com.au/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=finding+your+Steam+Id
