### ISSUE TITLE
Severe sim performance degredation if using defined areas.

### ISSUE THREAD

**Issue by jpcsupplies** [midspace/Space-Engineers-Admin-script-mod#174]
Not sure why this is now suddenly an issue was fine 2 weeks ago.  protection area definitions seem to kill the server sim speed.

Just spent 2 hours loading/unloading my server map on a local DS to track this down..
no changes seemed to help until i deleted the areas file then problem went away. 

May be related existing logged issue - tho nothing jumps out at me. Seems to be whatever method is being used to poll the safe harbor regions murders the server (and client too oddly) sim speed, to the tune of 0.90 of the sim speed being consumed.

Example -
dedicated server runs at 0.07 sim speed until the following file is deleted entirely while server is stopped, then server is restarted.  The protectionenabled flag seems to make no difference true or false.
Areas_ramblers lawless void.xml

(hit edit button to get file formatting back, seems to wrap it after posting)
`<?xml version="1.0" encoding="utf-16"?>
<ProtectionConfig xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Areas>
    <ProtectionArea>
      <Name>core</Name>
      <Center>
        <X>0</X>
        <Y>0</Y>
        <Z>0</Z>
      </Center>
      <Size>400</Size>
      <Shape>Sphere</Shape>
    </ProtectionArea>
    <ProtectionArea>
      <Name>BlackRock</Name>
      <Center>
        <X>-13976</X>
        <Y>-82311</Y>
        <Z>45130</Z>
      </Center>
      <Size>5000</Size>
      <Shape>Sphere</Shape>
    </ProtectionArea>
    <ProtectionArea>
      <Name>TradeHub</Name>
      <Center>
        <X>7633</X>
        <Y>-34735</Y>
        <Z>22730</Z>
      </Center>
      <Size>5000</Size>
      <Shape>Sphere</Shape>
    </ProtectionArea>
  </Areas>
  <ProtectionEnabled>false</ProtectionEnabled>
  <ProtectionInverted>false</ProtectionInverted>
</ProtectionConfig>`

**Comment by midspace** [comment]
Been testing on the `Tucana 2.0` server.
The issue only manifest with:
Shooting exposed Armour blocks with the rifle.

It does no occur when:
Grinding anything.
Shooting functional blocks (glass, lights, command chairs, projector) with rifle.
Shooting armour blocks behind a small functional blocks with rifle.

It is significantly worse with ship grids with large am amount of blocks.

**Comment by midspace** [comment]
I'm guessing we are falling afoul of performance issues here because it is an Armour block, and has no FatBlock information.


https://github.com/midspace/Space-Engineers-Admin-script-mod/blob/master/midspace%20admin%20helper/Data/Scripts/midspace.adminscripts/Protection/ProtectionArea.cs#L65

Calling CreateFromObjectBuilder is probably a bad idea to do with each bullet hit.
https://github.com/midspace/Space-Engineers-Admin-script-mod/blob/master/midspace%20admin%20helper/Data/Scripts/midspace.adminscripts/Protection/ProtectionArea.cs#L86

**Comment by midspace** [comment]
I've published a fix.
It'll need to be tested by restarting the server.

**Comment by Spcemarine** [comment]
Happy new year ;)

**Comment by Zataralee** [comment]
Looks to be working the way it should now. Thanks for the visit this morning and the update. Tucana 2.0 welcomes you back any time. Happy New Year!! :)

**Comment by jpcsupplies** [comment]
Interesting that you mention the rifle thing.  I also noticed after disabling the safe harbor regions that there was an active turret in one of them when checking in space master after disabling.  

It probably isn't practical but assuming the gunfire was a factor, another possibility is make turrets auto-disable when in or in range of a protected region target.
