### ISSUE TITLE
Adding mod - cant find server

### ISSUE THREAD

**Issue by Silvrav** [midspace/Space-Engineers-Admin-script-mod#180]
Hi

So I wanted to add this Mod to my existing server.

Went to existing sandbox world and

removed : `<mods />`
replaced with:

```
<Mods>
    <ModItem>
      <Name>316190120.sbm</Name>
      <PublishedFileId>316190120</PublishedFileId>
    </ModItem>
</Mods>
```

After saving and uploading back to server, restarting server and trying to connect via direct connect and my server IP it tells me Game no longer available....

Remove the above and I can join the game again.

Host is gameservers.com

**Comment by midspace** [comment]
Those changes look correct.
What program did you use to make the changes?
When you changed it back, did you use the same program, or simply restore from a copy or backup?

**Comment by Silvrav** [comment]
Hi @midspace

Stopped server
Used filezilla to FTP in and go to save file
Used notepad to edit and add mod.
Saved-uploaded mod. restarted server
Tried to join via direct link in game and tells me game not available anymore.

I used the same method above to remove the mod and just add <Mods /> back in via notepad. Restarted server and can then join

**Comment by Silvrav** [comment]
So i am now reading that sometimes a mod can take a while to DL. so have reinstated the mod in the sandbox file and will give it 5mins after restart to see if anything happens

**Comment by Silvrav** [comment]
ok, can report back that is not the issue....waited 15min and then restarted the server again...still not working

**Comment by khamseen** [comment]
Are you using standard Notepad or Notepad++? Standard Notepad has a habit of changing formatting which can break xml.  Your log file would probably have some indication of why the server has failed to start.

**Comment by Silvrav** [comment]
@khamseen  standard notepad.
Thing is, other things that I added worked.

will try in notepad++

Where can i find the log file?

**Comment by khamseen** [comment]
I've never used your host but the log file is usually in main Space Engineers directory on servers. It's simply called SpaceEngineers.log

**Comment by Silvrav** [comment]
![capture](https://user-images.githubusercontent.com/29704893/27540859-f185edb2-5a81-11e7-9ae5-1dfcae9fdade.PNG)
Here is the notepad++ screenshot.

and here is the log

![image](https://user-images.githubusercontent.com/29704893/27540896-23b7742c-5a82-11e7-8839-5ce28cb4a6e3.png)

**Comment by Silvrav** [comment]
So it says local mods not allowed??? how does this get fixed?

Must i download entire save game to my local drive, apply mods and upload again?

**Comment by khamseen** [comment]
Local mods just means they can't be in an extracted format and have to be workshop links which that is so I'm not sure why it's complaining about it. It's been a while since I manually added mods to a server via the sbc file but that should be working and it should automatically download the mod to the appropriate directory on your server. 

Do you have the ability to input mod IDs via the control panel website interface for your server? If so, it might be worth trying that method just in case.

**Comment by Silvrav** [comment]
@khamseen unfortunately not. Only FTP access

**Comment by khamseen** [comment]
At this point my only suggestion would be to open a support ticket with your server hosts. What you've done should have worked so unless midspace has any other ideas, I've no idea why it's causing a problem.

**Comment by Silvrav** [comment]
@khamseen thanks...will see if @midspace has some ideas

**Comment by midspace** [comment]
Silvrav, are you able to attach the entire log file?

**Comment by jpcsupplies** [comment]
Ok - this is how a steam mod is formatted - notice the spelling of "PublishedFileId"

You were spelling it "PublishFileId"  (missing the "ed")

`    <ModItem>
      <Name>627371699.sbm</Name>
      <PublishedFileId>627371699</PublishedFileId>
    </ModItem>
`

This is how a local mod is formatted - note the lack of a published file ID -
because it didnt recognize "publishfileid"  as a valid identifier, it ignored it and just saw the "name" and assumed it was a local mod.
`    <ModItem>
      <Name>Economy</Name>
    </ModItem>`

**Comment by midspace** [comment]
Yes, I didn't see that.
The sample text provided in the opening post does not match the screen shot of the `Sandbox.sbc` file.
The misspelling will cause the game to think it is a local mod.

This is the correct spelling:
```
<Mods>
    <ModItem>
      <Name>316190120.sbm</Name>
      <PublishedFileId>316190120</PublishedFileId>
    </ModItem>
</Mods>
```

**Comment by khamseen** [comment]
Wow, well spotted. I even copied the blurb from the first post to make sure it was right, didn't notice the misspelling in the screenshot.

**Comment by Silvrav** [comment]
Excellent and thanks for spotting that!

have just made the changes and will update if it worked! Thanks alot @jpcsupplies and all the others trying to assist

**Comment by Silvrav** [comment]
It worked! thanks guys...last question..I dont see the storage folder where I need to edit the MOTD file for message of the day? as the location changed?

**Comment by midspace** [comment]
The Server should create the folder. It will probably only appear after the first time you save the world with the mod active.

**Comment by Silvrav** [comment]
Great thanks @midspace. will save now and test

**Comment by Silvrav** [comment]
done and dusted! all working! thanks everyone!
