### ISSUE TITLE
[Request] - Switch to Station/Ship

### ISSUE THREAD

**Issue by Jentara** [midspace/Space-Engineers-Admin-script-mod#186]
A command that would switch a large ship, by name or in crosshairs, to a station, or to a ship.

**Comment by midspace** [comment]
I've made a request for Keen to add this to the Space Master ability.
There is a feature in the Space Master, that allows Admins to access any terminal, however the convert to Ship or Station is still disabled.

**Comment by midspace** [comment]
This feature should be available to all Admins via Space Master now.

**Comment by midspace** [comment]
Add commands

**Comment by midspace** [comment]
The new commands should now be available in the mod.
`/tostation` and `/toship`
