### ISSUE TITLE
delobjects isn't removing floating stone ore

### ISSUE THREAD

**Issue by ChrisM-Rogers** [midspace/Space-Engineers-Admin-script-mod#187]
I've used the collect command to pull nearby stone ore in one place and wanted to delete it with `/delobjects` but nothing happened. I believe this should remove the floating stone ore? At least the command description suggests it should.

**Comment by ChrisM-Rogers** [comment]
Hum, it seems `/invclear` isn't working either.

**Comment by midspace** [comment]
The fixes have been released into the mod.
This will require servers to be restarted if these commands need to be used.

**Comment by ChrisM-Rogers** [comment]
@midspace Thanks, I'll check it out :)

**Comment by ChrisM-Rogers** [comment]
Working perfectly. Thanks!
