### ISSUE TITLE
Suggestion to add Feature.

### ISSUE THREAD

**Issue by woodzykiler** [midspace/Space-Engineers-Admin-script-mod#188]
Would it be possible to add a /gridslist command for players. so they can find there own lost ships?
Also, Is there a passable way you can make grids unbreakable if a player is offline for more then 8 mins?
Can you add an advanced clean up feature? that can be defined in the config you have?
Example to keep grids
Beacon or Has not been online in 20 days or a rename like Playername_Ship name (look for Playername_ )
This will be good for lost wolf, spider, crashed grids, spawnships, and other things.

**Comment by midspace** [comment]
The problem with creating a /gridslist command, is how to classify a ship they own.
In a PvP server, if another player has already hacked through most of their ship blocks to take control of the ship, who would you say owns it?
Adding a method to find a grid without a causing more grief to other players is a complex issue.

I have no plans to add a clean up feature to the Admin helper mod.

Making grids unbreakable while a player is offline is possible, but this also can be misused.
Other online players can use another other player's ship as battering rams against online adversary's and drone/cargo ships.
