### ISSUE TITLE
Wrong values for Environment Hostility

### ISSUE THREAD

**Issue by jb-aero** [midspace/Space-Engineers-Admin-script-mod#191]
Super minor, but I was wondering why when playing on "normal" it displays as "armageddon". Found it here, looks like "armageddon" would then display as "offline". https://github.com/midspace/Space-Engineers-Admin-script-mod/blob/master/midspace%20admin%20helper/Data/Scripts/midspace.adminscripts/UserCommands/CommandSettings.cs#L60

**Comment by midspace** [comment]
Nice catch!
I'll fix that right away.
It'll go out in the next release this week.

**Comment by jb-aero** [comment]
Much appreciated! Now if only I could figure out which mod was causing normal hostility to *behave* like armageddon...

**Comment by midspace** [comment]
The fix was released. Closing the issue.
