### ISSUE TITLE
MOTD features

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#22]
Need to be able to turn off MOTD, as not all server administrators will want to use it.
Single players will not want it either.
Off will need to be the default setting.

**Comment by Spcemarine** [comment]
It won't shoe

**Comment by Spcemarine** [comment]
*It won't show if it is not set.

//Damned smartphone -.-'

**Comment by midspace** [comment]
Would like to make the motd specific to the game world, not the server.
Much like...
https://github.com/midspace/Space-Engineers-Admin-script-mod/blob/master/midspace%20admin%20helper/Data/Scripts/midspace.adminscripts/CommandTeleportList.cs

Also, some (pseudo) Environment Variables to the motd text.
For, world name, server ipv4 address/port, server name, game description.
Some of this I don't think is available right now, but can be provisioned for.

**Comment by Spcemarine** [comment]
Yeah, I see it makes more sense if it is specific to the world.

Variables such as %SERVER_NAME%, %WORLD_NAME% are a very good idea. I'll see what could be useful and is currently available.

**Comment by midspace** [comment]
Discovered an issue with OnEntityAdd(IMyEntity obj) and IMyCharacter.
It will trigger every time a player exits a cockpit.

**Comment by Spcemarine** [comment]
We'll just have to set CommandMessageOfTheDay.ShowMotdOnSpawn to false when the motd was shown. I just forgot to do that.

**Comment by Spcemarine** [comment]
Seems like I didn't forget it. Did the motd show up when you left the cockpit or did you just assume that?

**Comment by midspace** [comment]
No, it was my test code that was firing off.
I've been working on a bunch of fixes for 067, and its taken me a while to check all my scripts and the Toolbox.

On thing I can say, if you have...

if (!_isInitialized && MyAPIGateway.Utilities.IsDedicated && MyAPIGateway.Multiplayer.IsServer)

Both Utilities and Multiplayer will have to be null checked.

if (!_isInitialized  && MyAPIGateway.Utilities != null && MyAPIGateway.Multiplayer != null && MyAPIGateway.Utilities.IsDedicated && MyAPIGateway.Multiplayer.IsServer)

**Comment by Spcemarine** [comment]
Ok, I hope you are not planning to release the motd feature along with the fixes. I'm working on the config file already and it is nearly finished. The cfg contains a suffix for the loaded cfg file that can be changed by the admin. It is easier to identify the file that way. Additionally the cfg file contains the path of the loaded world, so it can be easily identified too. Of course the name of the cfg file contains the world id.
May I ask where you get your information on the update?

**Comment by midspace** [comment]
So, I need to strip out the MOTD for tomorrows release?
I'm in the closed test group. I can't say any more than that. NDA and all.

**Comment by Spcemarine** [comment]
I should be able to commit the cfg today afternoon. I'll just comment out the new functions  that are mote complex and should be tested so that it only contains the motd file suffix. Ok with that?

**Comment by midspace** [comment]
"Mote complex"?
I can comment it out before I publish the release, unless you are confident its ready.
No need to check in at this point, unless its ready.

**Comment by Spcemarine** [comment]
*more complex :D
It should be ready but I didnt have enough time yesterday to test and debug it properly. I also included a way to change the security of commands but that should be tested very thoroughly before releasing it. That's the code I would comment out.

**Comment by Spcemarine** [comment]
Just noticed I forgot to mention that I added the 'environmental variables':
%SERVER_NAME%, %WORLD_NAME% and %SEVER_IP%
They refer to the similarly named fields in the dedicated server config.
