### ISSUE TITLE
Add private message system

### ISSUE THREAD

**Issue by Spcemarine** [midspace/Space-Engineers-Admin-script-mod#24]
Send a private message with /msg. Also sometimes referenced as 'whisper system'.

Thinking about using @<username> <message> instead. Or both?
May be useful if we implement 'whisperpartners'. 
@@ <message> -> sends a message to your whisperpartner
@@@ <username> [message] -> sets the wisperpartner and optionally sends him a message

Options to extend it later:
@@@@ [message] -> sets your whisperpartner to the last player who 'whispered' to you and optionally sends him a message
@@@@@ <message> -> sends a message to the last player who whispered to you

@? -> returns your current whisperpartner

By the way: we used this pm system on a mc server and it was quite popular.

**Comment by midspace** [comment]
Both I would say.
One of the general things I have loved about Windows since Windows 95 came out, is that there is usually more than one way to find or do something in the operating system.
This works well, as people have certain traits that make them prefer one way or another for a variety of reasons.

**Comment by Spcemarine** [comment]
Dicovered that I can't type @ in chat. Using # instead.

**Comment by midspace** [comment]
German keyboard issue, or game issue?

**Comment by midspace** [comment]
I'm not sure, but there appears to new API methods in the Sandbox.ModAPI.IMyMultiplayer interface.
SendMessageTo....()
It might provide a better messaging method for what we are doing.

**Comment by Spcemarine** [comment]
Yes, I'll take a look at the SendMessage methods. It's a issue with keyboard regions. In Germany for example we use 'AltGr + Q' to type an @ and AltGr does not work in Space Engineers. There is already a bug report in the forum so I hope it will be fixed soon. Furthermore we can't use '#' because it is not writable in some regions. Just like '@' it requires AltGr to type it. I'll change it back to @ and wait for a fix.

**Comment by Spcemarine** [comment]
SendMessage works well, I'll change the connections to it.

**Comment by Spcemarine** [comment]
Just to let you know: If something breaks and you have to release an update, it'll include the change to use the SendMessage...() methods. Of course I'll test it as thoroughly as I can.
While implementing private messages I thought about implementing escaping to be able to type in names with white spaces. But since the steam name can contain any characters, we can't specify an escape character and I don't like manually escaping the escape character with '\'. '/msg "Screaming Angel" Hello' would be fine but if the name was Screaming "Angel" it must be changed to '/msg "Screaming \"Angel\"" Hello' and that's just weird and unusable. I'd rather implement a listplayers command, that just work like /status without giving the player more information than the displayname (we could also change the status command so that admins receive more information and rename it to listplayers or define an alias like that..). Additionally it would be nice to specify only a part of the player name. If only one match is found I'll be shown a dialog to confirm that I want to send the message to that player. If more matches are found a hotlist with the matches is displayed. So the user has just to type the command and will be lead through the different steps without any knowledge required. Anything wrong with that concept?

**Comment by midspace** [comment]
Can't we convert a name into a steam id, and pass that instead?
I know the /pardon won't work that way, and unfortunately it would require manual intervention on the file to pardon a player with a unicode name regardless.

I haven't found any hard breaking changes, but that doesn't mean they won't slip in last minute changes, or have any soft changes that only fail when you call them.

**Comment by Spcemarine** [comment]
We always pass the steam id except for /pardon. We could implement a hotlist for pardon to allow removing players with unicode names without having to edit the file manually. 
It's just for the user input, not for the messaging. At the moment, if I use '/msg Screaming Angels Hello' it will try to send the message 'Angels Hello' to the player 'Screaming'. If I allow escaping with regex to make something like '/msg "Screaming Angels" Hello' possible a playername that contains " and white spaces will not be recognized because the name ends after the second " or the white space. If I do a manual escaping so that the users (not only admins) have to type a \ in front of every " the name contains I'm sure they won't really get that (some will understand it, others not, too many DAUs out there).
Since the hotlists are only available for the admins we either need a hotlist with player names for the normal users or we match the input with the names of players that are online so that I can type '/msg Screaming Hello' and a dialog will open and ask me if I really want so send the message 'Hello' to 'Screaming Angels'. If I make the mistake that I execute the command '/msg Screaming Angels Hello' I'll be asked if I want to send the message 'Angels Hello' to 'Screaming Angels' and I can cancel the message and correct it. If there are several matches for the input, e.g. Spacemarine and midspace if the input is 'space', you'll be given a hotlist that works only for that command.

**Comment by midspace** [comment]
Ah, yes sorry, I understand now.

You should be able to use the /status command.
The /status command is intentionally a User level command.
This allows other players to see the steam id of other players in case they get griefed on a public server, allowing them to report it to admins at a later time.

We could end up adding our own /report command at some stage

**Comment by Spcemarine** [comment]
Oh, I assumed that the status command is available for admins only like the other hotlists. Ok, then I'll use it and maybe implement the matching later. It's just useful and should be easy to realize.

**Comment by Spcemarine** [comment]
I didn't experience any issues with the pms but since I'm not really good with regex you should take a look at them. I just have no experience with it.
The implementation allows to send a pm to yourself. I don't think there is a reason to forbid it, it looks a bit weird but it's good for testing and it's not like you can do any damage to anything by sending a message to yourself.
