### ISSUE TITLE
Anti grief command

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#27]
Read this first.
http://steamcommunity.com/app/244850/discussions/0/622955136054091917/

This may be very questionable.
Using the server clent messaging, send a message to a particular player that causes an exception.
The method that throws the exception should mimic the Keen namespace and function names so it appears like a native exception in the logs.
The steamid of the player should be stored, so on subsequent attempts to join the game, the message is sent again (from the server).
The host player should be excluded from the action at all stages, to prevent possible hijacking of the mod.

The truth is, yes, you can modify the game so it ignores Kick and Ban commands.
Ignoring Friend checks is also possible, as all checks occur client side, allowing a client to connect regardless of what the server wants.

**Comment by Spcemarine** [comment]
This shows how bad the server code actually is. The server must always be the highest instance.
However, I agree that it is questionable but it's rather justified as long as you are able to modify the game like this.
I wonder if it is possible to mimic the method names. We cannot have different namespaces in our mod, right? And using the games' methods is also useless. The hacker can surround the method that's causing an exception with a try/catch block and fix it.

**Comment by midspace** [comment]
The following code:

    namespace A8DB07281BA741DFB48BE151DDBFE24F
    {
        using System;

        [Sandbox.Common.MySessionComponentDescriptor(Sandbox.Common.MyUpdateOrder.BeforeSimulation)]
        public class D384FFC3B4164AB29EE47720094B109E : Sandbox.Common.MySessionComponentBase
        {
            public override void UpdateBeforeSimulation()
            {
                if (PlayerTerminal.DropPlayer)
                    throw new Exception();
            }
        }

        public static class PlayerTerminal
        {
            public static bool DropPlayer;
        }
    }

will cause the following exception log detail.
2015-02-05 11:49:12.677 - Thread:   1 ->  Exception occured: System.Exception: Exception of type 'System.Exception' was thrown.
   at A8DB07281BA741DFB48BE151DDBFE24F.D384FFC3B4164AB29EE47720094B109E.UpdateBeforeSimulation()
   at AAC05F537A6F0F6775339593FBDFC564.D580AE7552E79DAB03A3D64B1F7B67F9.F672BBF9E192151CE8FD7E91E62B997D()
   at AAC05F537A6F0F6775339593FBDFC564.D580AE7552E79DAB03A3D64B1F7B67F9.EC90B1C44E3C361983D093F355FF0CC8(MyTimeSpan 9916A9BA14FB0BB1A36908E2E8C15A74)
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.AB24E6EF4B69C38D90087D40DE00338E()
   at 168638249D29224100DB50BB468E7C07.7BAD4AFD06B91BCD63EA57F7C0D4F408.2457E95BE2F0D1F1A4A009B2B1DBBDA4()
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.858DA51EB20785A82D9A03614304088A.0187A29A24275EC024A192E7E235CC2E.9C41E76459B99591F991CBA0833BD17E()
   at 168638249D29224100DB50BB468E7C07.6E0E814918D8AD6B2DC9CA5005102256.82BAF25184DF43AB0406F85A749A839A(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.82BAF25184DF43AB0406F85A749A839A(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.246E732EE67F7F6F88C4FF63B3901107(Boolean FF8E4184144DE7049FF5EC07D594DAB6, Action 8CF1B812E214DD1C51DD894D4C05D44A)
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.523C8831DA5DAB3A19F6D33A2C6437B5(String[] 954514EA42AFFE4302240CE14E5D6683)
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.0D8AAA624C2EEA412F85ABB3AEFAF743(String[] 954514EA42AFFE4302240CE14E5D6683)

**Comment by Spcemarine** [comment]
Seems like I mixed up some restrictions. Generally it works for me, but like I said I only could try it out with myself but since I used the /slay command as a base for the player name processing it shouldn't require further testing. I'd recommend to release it as soon as possible so that we/I can fix upcoming issues till Friday and it is ready when you are on holidays.

**Comment by midspace** [comment]
I'll make sure to do some through testing tonight then before I release it.
Two (of my) expectations are:
Run a dedicated server. Connect to dedicated server. Be able to kick yourself.
Run a listen server. Be blocked from kicking host. The Host as the server should be protected.

One last thing, when using string.Format, it takes native Type values, and formats them internally.
ie., this...
string.Format("{0}:true", findPlayer.SteamUserId.ToString()));
should be this...
string.Format("{0}:true", findPlayer.SteamUserId));

because the "{}" can apply a format.
ie., float val = 123456.7890f;
"Distance: " + val.ToString("#,##0")
is the same as...
string.Format("Distance: {0:#,##0)", val);

**Comment by Spcemarine** [comment]
It won't work on listen server since the connection handling won't be initialized. You could try to change the ChatCommandLogic so that it first initialize as a server instance an then as a client. It could happen that I have used the same fields on client and on servers so there might be some errors or malfunctions due to that but I'm not sure.
I wanted to implement this yesterday but I had no time left. Hopefully I have enough time to do it today.

**Comment by midspace** [comment]
Tested on both Dedicated Server with two players, and Listen server.
It doesn't work.
No errors.

**Comment by midspace** [comment]
From what I can tell, the /forcekick is sending the message to the server, not to a client.

**Comment by Spcemarine** [comment]
The connections always run through the server. There is no direct connection between clients. Like I said: the server is supposed to be the highest instance. The server checks if the player is an admin it won't send him the command to throw an exception. Is that the case that you were admin? Thing is if I set the security to 'User'  to test it on me, it works.
Problem with LS was more than just one. Phew... Difficult to test it thoroughly alone. Can't display motd on join because the event on spawning the character is not called.

**Comment by midspace** [comment]
As long as it is the server checking for isAdmin, and not relying on the client, as a hacked client could make themselves an admin, just not in the eyes of the server.
Add the worldid to the logger, as there is the minor chance we leave it on and someone runs this on two service instances. It'll throw a file lock exception. (I was thinking we need a logger in there).

Does this MyAPIGateway.Utilities.ConfigDedicated.Administrators, actually work on the server?
I've never seen it work on a client.

**Comment by midspace** [comment]
I was going to ask about the ForceBan. There is a return in the middle of the code.

**Comment by Spcemarine** [comment]
The logger was just for debugging stuff on DS. I can't display things easily with a command so I thought we'd just turn it off before releasing. If you want it to log on default just add the world ID to the filename. And yes the ConfigDedicated works for the DS instance.
That return is not supposed to be there. Just removed it.

**Comment by midspace** [comment]
It's now published.
I would be nice if we could get these working for Listen Servers also.

**Comment by Spcemarine** [comment]
Actually it should work on LS... You tried kicking s.o. who is not the host?

**Comment by midspace** [comment]
Just tried /forcekick, it works on LS.
Trying /forceban in a moment.

**Comment by midspace** [comment]
/Forceban is not working.
Causing an exception on the host. Caught by our exception handling.
System.NullReferenceException: Object reference not set to an instance of an object.
at midspace.adminscripts.CommandForceBan.Invoke(String messageText)
at midspace.adminscripts.ChatCommandService.ProcessMessage(string messageText)

**Comment by midspace** [comment]
Looks like it is my fault when I cleaned up the code.

**Comment by midspace** [comment]
Fixed and checked in.
I've retested, and it works. Good work!
I'm just too distracted in preparing for the trip. -_-
