### ISSUE TITLE
CollectObjects command does not sync on servers

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#29]
The /CollectObjects appears to work fine on single player,
but on Dedicated servers, the objects change somehow and stop obeying the rules for normal floating objects. Ie, Collector does not recognize them, and they sit inside.

I'm not sure if it's the Physics Speed, or position that is not syncing correctly at this stage.

**Comment by midspace** [comment]
SetPostion() is causing the sync issue on Servers.
Have raised a bug with KeenSWH in the CTG.

**Comment by midspace** [comment]
It that the sync issue with SetPostion() on floating objects goes both ways.
Have tried setting it on the server, but it doesn't sync on the clients.
Setting on a client, doesn't sync back to the server.

**Comment by Spcemarine** [comment]
It may be a little bit inappropriate but we could try to close the entities and respawn them at the new location. Could cause a lot of traffic but might work.

**Comment by midspace** [comment]
It might be a good substitute. The only concern, is we're causing a re-ordering of the entity stack, and older floating items are supposed to be targeted for cleanup if the floating item limit is reached.

Also, I've no idea if the Close() or Delete() commands are server friendly.
I've create a /DeleteShip command which I've yet to test on a server. There is one bug so far, and that is it doesn't eject players early enough before deleting the grid. Need to somehow separate the two to give enough time for players to be ejected.

**Comment by midspace** [comment]
it looks like entity.Delete() and entity.Close() does not sync from server to clients either.
It may be we have to implement this command across the server and all clients to sync it properly.
The same will happen with /DeleteShip.

**Comment by midspace** [comment]
To delete a Ship, apparently you should not call cubeGrid.Delete() or cubeGrid.Close().
Instead you should call cubeGrid.SyncObject.SendCloseRequest(), as this will sync across all sessions.

With the pull objects, instead of deleting and recreating the floating objects, I've implemented a SetPosition() that is sent to every session.
It's not perfect, as there may be some slight desynchronization due to the timing, leaving floating objects in slightly different positions.
