### ISSUE TITLE
Session commands to be changed on all Clients

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#32]
The /cargoships, /copypaste, /creative will need to be changed from a command that only executes on the current client, to a command that runs on all connected sessions, especially the server.

**Comment by midspace** [comment]
/creative, /cargoships and /copypaste send a message to the server that
as a result, sends a message to all clients
- the message about the new value of the setting is displayed to the
admins (or is it supposed to be sent to all players?)

As long as the setting is also applied on the server.
Yes, the message should be sent to ALL admins present in game.
I'm not sure what we should do about players currently in the process of connecting to the server. They will probably not get the message.

I'll probably be without internet access for a few days, and I don't have a lot of time this morning to test scenarios.

**Comment by Spcemarine** [comment]
All clients receive the information from the server that the setting has changed but only the admins are informed about it via chat. For clients in the process of connecting I could add it to the initial data.
