### ISSUE TITLE
/smite command to be run on individual client

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#33]
The /smite command creates an meteor that hits the designated player.
On a MP or DS, because the meteor is created on the session of one client, it's location my not exactly match up with the location of the other player on their client.

We can either look at changing the chosen vector of the meteor, so it always comes from in front of the player's direction of travel.

Or, we spawn the meteor of the actual client of the player to be affected, thus making sure it's location is always right.

**Comment by Spcemarine** [comment]
I think the second option was better, let's see if it really works...

**Comment by midspace** [comment]
You should be able to test on a DS.
Try with the currently published mod first for comparison, so you can see the issue.

**Comment by Spcemarine** [comment]
But if I execute the command it will work anyways. I'll look if I can find s.b. to test it with.
