### ISSUE TITLE
Invisibility command

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#36]
Command for making admin player invisible (at least to automated weapons systems and sensors), or and maybe some sort of noclip ability.
Admins want a way of checking up on players without been affected by guns.

Though adding the ability for a admin to use the spectator mode when it's disabled on a server may be a good alternative.

**Comment by midspace** [comment]
There are still some limitations that are listed in the description.
The primary been, automated weapons still track and shoot you.
I fooled around with the PersistentFlags, which can remove the player
shadow and thrusters but I'm unsure how stable this is.

**Comment by Spcemarine** [comment]
Come to think of it, we can also implement god mode. At least you won't get killed by weapons while stalking someone...

**Comment by midspace** [comment]
god mod? make it so!

**Comment by zrisher** [comment]
Yeah that would be amazing. The only way to do it would be using the damage tracking hooks right?

**Comment by Spcemarine** [comment]
Right, that's the only way but it is quite simple.

**Comment by zrisher** [comment]
Looking forward to seeing the implementation. : )

**Comment by Spcemarine** [comment]
It won't take long, but it's almost 3:00 am now so I think I'll rather do it tomorrow. ;)

**Comment by midspace** [comment]
The current code that checks for viable targets as at today does the following checks:
```
if (myEntity is MyDebrisBase || myEntity is MyFloatingObject || (myEntity.Physics != null && !myEntity.Physics.Enabled) || myEntity.GetTopMostParent(null).Physics == null || !myEntity.GetTopMostParent(null).Physics.Enabled)
		{
// remove from target list
```

Turret code is not accessible to tell it to ignore a target, apart from removing the physics of the entity.
This is not a viable solution with a player.

The only working suggestion is for the Admin to use Spectator mode.
From what I have seen, all Admins get the Spectator mode enabled automatically even if it disabled on the server.
Most of the Admin helper commands have been enabled for use in Spectator mode as of a couple of months ago.

The only limitation however, is spectator view doesn't always download to the player the content.
You can move your player closer to the action, and then use Spectator view to do whatever you need.

**Comment by mikeloeven** [comment]
Have you considered submitting an API update to keens git hub ?

**Comment by midspace** [comment]
Previous attempts to submit changes to git haven't gone well with us as they have been knocked back for various reasons.
Typically it's been easier to request a feature and have it added by the Keen developers.

Integrating a code to disable weapons for specific targets sounds like a more complex issue, and that is disregarding whether Keen even want such a feature.

**Comment by midspace** [comment]
The current Space Master is more than adequate now for replacing this, and invisibility is next to impossible.

**Comment by mikeloeven** [comment]
Holy Necromancy Batman This was still open ?
