### ISSUE TITLE
Stop command does not work on some ships.

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#5]
Investigate and fix.
Maybe @Spcemarine commandbox code offers a different approach that works.

**Comment by Spcemarine** [comment]
I was using IMyEntity.Physics.ClearSpeed(). Do we have an object on which the command isn't working? Just to test if that method would work.

**Comment by midspace** [comment]
Okay, I've just checked ClearSpeed(). It does exactly what I was doing before.
I need to find one of those floating ships that refused to stop, and try examining it again.

**Comment by midspace** [comment]
Have moved the stop and stopall to run on the server, which appears to have fixed any sync issues.
