### ISSUE TITLE
/switch on/off ship cube commands

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#51]
turn on/off:
- weapon systems 
- projectors
- programmable blocks
- timers
- production (refineries, arc furnaces, assemblers)
- power (reactors, batteries)

on the targeted ship or ship number.
if hash (#) is not used, apply to cubes in range instead.

possibly use cases:
/switch #number weap on
/switch #number proj off
/switch #number prog on
/switch #number prod off

**Comment by midspace** [comment]
Originally from PhoenixX 
http://steamcommunity.com/workshop/filedetails/discussion/316190120/616188677641135375/?tscn=1425033046#c617329150704397735

J] disarm <#> command - basically turns off all found turrets in range #

K] rearm <#> command - basically turns on all found turrets in range #

**Comment by midspace** [comment]
This is practically done. The command has been implemented globally, and not to target any specific ships.

I'm not sure if there is much point in targeting specific ships, and the general need has been to turn whatever it is off everywhere.

We could look at further refining it though, like Turrets only, or Refinery only.

**Comment by zrisher** [comment]
Very nice, excellent feature to have.

**Comment by midspace** [comment]
Additional request for the following:
`/switch drill / lights / rotor / piston `
