### ISSUE TITLE
MOTD does not show in creative and on listen servers

### ISSUE THREAD

**Issue by Spcemarine** [midspace/Space-Engineers-Admin-script-mod#53]
Original message from PhoenixX:
"Is it my imagination or does MOTD act oddly, or even prevent exiting cryopods in some cases?
Sometimes they don't pop up until i enter and exit a cockpit etc. Wierd. Not sure whats going on."

**Comment by Spcemarine** [comment]
Took a look at it. I guess it has nothing to do with cryopods. It's just that the character is created too early in creative when the game isn't ready yet. The same goes for the host of local servers.
'Sandbox.MySandboxGame.OnSessionReady' might be useful, but well, we can't access it. -_-

**Comment by midspace** [comment]
Internal code indicates there is a limit of 4096 bytes when sending a message between servers and clients.
When we package and encode the motd text in byte[] to send to clients, this limit is reduced to less than 2048 characters of text.

**Comment by Spcemarine** [comment]
I don't think that the guys experienced this issue but it must be fixed.

**Comment by Spcemarine** [comment]
Hmm... I think about exposing some events like the one mentioned above to the API. Maybe I also add events like when s.b. changes the colors of blocks and when s.b. grinds or welds a block. Just some anti griefing stuff and we could combine that with permissions. But that might take some time.
