### ISSUE TITLE
MOTD encoding

### ISSUE THREAD

**Issue by Spcemarine** [midspace/Space-Engineers-Admin-script-mod#54]
There is something wrong with the encoding of the MOTD. The error occurs when we send it via messages. Characters such as ö,à,é,ß are displayed as "�".

**Comment by midspace** [comment]
It worked before splitting up the message?

**Comment by Spcemarine** [comment]
No, it didn't work before.

**Comment by midspace** [comment]
I'm assuming you can type them into the chat box and other fields.
We'll have to enforce Unicode encoding on the byte conversion of the message content.

**Comment by Spcemarine** [comment]
It also works if I display the content directly from the file and I couldn't reproduce the issue with other commands like msg.

**Comment by Spcemarine** [comment]
Somehow this was fixed with 1.83 or something. However, it is working now.
