### ISSUE TITLE
Delete ship command.

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#6]
Add the ability to delete an entire grid.

Will have to delete attached grids also (Rotors and Pistons).

**Comment by midspace** [comment]
Rotor and piston connections should be optional.

Have to make sure all players are ejected first, as I have read there are bug created on the players.
See. http://forums.keenswh.com/post/show_single_post?pid=1286203557&postcount=123

**Comment by Spcemarine** [comment]
So we have to get the objectbuilder of the cockpit to access the pilot and eject him. I wonder if passenger seats also have the MyObjectBuilder_Cockpit as the objectbuilder type.

**Comment by midspace** [comment]
And remotes.

Sorry, just got wifi for a few minutes.

**Comment by midspace** [comment]
We could check all the player entities top most parent if they are that ship.
It doesn't check for a pilot who is remoting another ship though.

**Comment by Spcemarine** [comment]
Or we just check if sb is controlling the ship for remote control and if he is sitting in a cockpit/passenger seat the following code we can modify the following code. "Pilot" is always the character sitting in the cockpit no matter what they control.

```c#
HashSet<IMyEntity> entities = new HashSet<IMyEntity>();
MyAPIGateway.Entities.GetEntities(entities, e => e != null && e is IMyCubeGrid);


foreach (IMyEntity entity in entities)
{
    if (!(entity is IMyCubeGrid))
        continue;

    var ship = entity as IMyCubeGrid;
    IMyControllableEntity[] cockpits = ship.FindWorkingCockpits();
    foreach (IMyControllableEntity cockpit in cockpits)
    {
        var cockpitCubeBlock = cockpit.Entity as IMyCubeBlock;
        if (cockpitCubeBlock == null)
            continue;

        MyObjectBuilder_CubeBlock entityObjBui = cockpitCubeBlock.GetObjectBuilderCubeBlock();
        MyObjectBuilder_Cockpit cockpitObjBui = entityObjBui as MyObjectBuilder_Cockpit;

        if (cockpitObjBui == null)
            continue;

        if (cockpitObjBui.Pilot != null)
            MyAPIGateway.Utilities.ShowMessage("Pilot", string.Format("Found {0} in a cockpit of {1}.", cockpitObjBui.Pilot.DisplayName, entity.DisplayName));
        else
            MyAPIGateway.Utilities.ShowMessage("Pilot", "No pilot found.");
    }
}
```

**Comment by midspace** [comment]
I'm backing out on the optional requirement for rotor and pistons, but it needs to be restricted to just them. Not connectors or landing gear.
