### ISSUE TITLE
Grinding of undestructible grids

### ISSUE THREAD

**Issue by Spcemarine** [midspace/Space-Engineers-Admin-script-mod#69]
There was the suggestion to prevent grinding on grids that have been set undestructible. However we cannot identify who is grinding since we only get the Sandbox.Game.Weapons.MyAngleGrinder if we get the entity for the AttackerId. Thus, an option to prevent everyone from grinding might not be a bad idea but it could cause confusion.

**Comment by midspace** [comment]
We could check for proximity to a grid with undestructible set.

Question is, can we prevent grinders from been used at all? Especially ship grinders.

**Comment by Spcemarine** [comment]
We can just set the amount of the damage to 0 if the grid is undestructible and the damage type is "Grind" . Very easy.

**Comment by midspace** [comment]
As of 01.094, indestructable blocks are protected from grinding.

See video from 4:07 onwards.
http://forum.keenswh.com/threads/update-01-094-new-small-ship-cockpit-model-collision-particle-effect-tutorial-scenarios.7365810/
