### ISSUE TITLE
Creative mode doesn't work any more

### ISSUE THREAD

**Issue by Nevrdid** [midspace/Space-Engineers-Admin-script-mod#70]
Since the today's update, the creative mode doesn't work at all. If we active it with /creative on, we need components for placing an objects. But if we do /creative on private, the creative mode immediately disable it.
Thanks for support.

**Comment by midspace** [comment]
I'm copying what I wrote on the forums.
It looks like KeenSWH have disabled the method we were using for changing the Creative/Survival, Copy/Paste, Weapons and Spectator modes on the fly whilst in game.
They were technically loopholes and never officially proper APIs, so I don't expect they will be put back in (as they were also been used by trolls and hackers). We'll have a look to see if there any other ways of switching these values, so please don't get your hopes up.

**Comment by Nevrdid** [comment]
kay, thanks, I hope you'll found an alternative cause repair problems changing the mode of the map create boring problems with conteners ^^'
Thanks for the fast answer and good luck for the next.

**Comment by midspace** [comment]
It looks like my initial assumptions were wrong.
The API has been cleaned up, and SessionSettings has been properly implemented.
As a result, the loophole we were using has been removed.
We just need to use the proper API now.

I'll try to have a release out in a few hours.
As I need also need to test these changes for the dedicated server.

**Comment by midspace** [comment]
It's not going smoothly.
On a dedicated server when switching on Creative mode privately, if the user tries to swap to any hand tool, it WILL crash the server.
As the SE Git source hasn't been updated recently, I can't track down the exact issue, so that means possibly disabling that feature.
Frankly speaking, this could be used to crash any server.
