### ISSUE TITLE
Motd variable %USER_NAME% and %USER_IP%

### ISSUE THREAD

**Issue by Spcemarine** [midspace/Space-Engineers-Admin-script-mod#91]
Those vars should be repaced after the client received the motd. But I'm not sure if we can actually get the user's IP.

**Comment by midspace** [comment]
I haven't seen anything for the User's IP address anywhere.

Considering what I know of how the communication channels work in the game code, I don't think any portion of the code knows what the client's IP address is.
There isn't much point from out perspective. We have a communication channel which we send and receive stuff. No need to know their address, as the game code is supposed to handle all that.
A client will connect to a Server. The Server *could* extract the IP address from the channel, but it doesn't.

I haven't tested, but more than likely, the System.Net namespace is not whitelisted.

All this will change once Keen implement RakNet of course.
