### ISSUE TITLE
Chat History

### ISSUE THREAD

**Issue by zrisher** [midspace/Space-Engineers-Admin-script-mod#93]
Have you guys discussed adding a command to display the last X chat messages?

**Comment by midspace** [comment]
Isn't /chat adaquate?

**Comment by zrisher** [comment]
Yep that's perfect, just tested. Sorry didn't know that existed, I don't see it documented anywhere in the wiki or on the steam page.

**Comment by midspace** [comment]
I've just fixed the wiki entries.
I think it was caught out some while back during a temporary issue with Steam not like the changes I was trying to make to the mod description and threads.

**Comment by zrisher** [comment]
*Perfect*, thank you!
