### ISSUE TITLE
Add /settings for normal users.

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#98]
I can't believe there isn't a panel or something to display the current in game settings.
A player can join a server, but have no clue what any of the current settings are.

**Comment by zrisher** [comment]
Another amazing idea. So many server admins manually maintain these lists in various places, leading to out-of-date info and a ton of upkeep time.

**Comment by midspace** [comment]
The command uses the game localized strings, except for 1 property which is actually from the Dedicated Server.

The AutoSaveInMinutes doesn't appear to be quite right, and still need more work.
